Bug fixes for networking lookups when Jenkins controller is running in Fargate
base2Services/ciinabox-pipelines pull request #158
Opened 2021-07-21 05:51 UTC by Guslington

### Improvements
- dont perform metadata and ec2 instance lookups if defaults are set
- refactor region lookup to use the region provider chain to support region lookup in fargate
- return better errors if networking details cannot be looked up
- apply fixes to packer, verifyAmiV2 and selenium methods

2021-07-21 06:52 UTC, Samseppiol requested changes

2021-07-21 06:52 UTC, Samseppiol commented on vars/packer.groovy
> +def lookupNetworkDetails(region) {
What is this?

2021-07-22 01:04 UTC, Guslington commented on vars/packer.groovy
> +def lookupNetworkDetails(region) {
removed

2021-07-22 01:06 UTC, Samseppiol approved these changes
lgtm

2021-07-22 01:20 UTC, merged